cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
path('api/add-to-cart/', AddToCartAPIView.as_view(), name='add_to_cart_api'),
path('api/cart-items/<int:user_id>/', CartItemsAPIView.as_view(), name='cart_items_api'),
path('update-cart-item-quantity/', CartItemQuantityUpdateAPIView.as_view(), name='update_cart_item_quantity'),

path('confirm/', confirm_order, name='confirm_order'),
path('user/orders/', user_orders, name='user_orders'),
path('user/orders/<int:order_id>/', order_details, name='user_order_details'),

]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('menu.urls')),
    # path('login/',login_user, name='login'),
    # path('logout/',logout_user, name='logout'),
    path('dashboarda/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',main_dashboard,name="main_dashboard"),
    path('product/create/', create_product, name='create_product'),
    path('product/update/<int:pk>/', update_product, name='update_product'),
    path('product/delete/<int:pk>/', delete_product, name='delete_product'),
    path('product/list/', product_list, name='product_list'),
    #Category
    path('category_list',category_list,name="category_list"),
    path('delete_category/<int:pk>',delete_category,name="delete_category"),
    path('create_category',create_category,name="create_category"),
    path('category/edit/<int:pk>/', edit_category, name='edit_category'),
    path('orders/new', new_orders, name='new_orders'),
    #users
    path('user_list',user_list,name="user_list"),
    path('create_user',create_user,name="create_user"),
    path('update_user/<int:pk>',update_user,name="update_user"),
    path('delete_user/<int:pk>',delete_user,name="delete_user"),
    
    #orders
    path('orders/performed', performed_orders, name='performed_orders'),
    path('orders/perform/<int:order_id>', performe_order, name='perform_orders'),
    path('order/<int:order_id>', order_details, name='dashboard_order_details'),
    
    path('login/',login_user, name='login'),
    path('logout/',logout_user, name='logout'),
     
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from menu.models import *

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cart')
    products = models.ManyToManyField(Product, through='CartItem')

    def __str__(self):
        return f"Cart for User {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} ({self.quantity}) in Cart for User {self.cart.user.username}"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Product, through='OrderItem')
    address=models.CharField(max_length=250)
    performed=models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order #{self.id} - User {self.user.username}"

    def get_total_price(self):
        total_price = 0
        for item in self.orderitem_set.all():
            total_price += item.get_item_total()
        return total_price


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product.name} ({self.quantity}) in Order #{self.order.id}"

    def get_item_total(self):
        return self.price * self.quantity
    
    

    

dashboard/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import os

# Create your models here.
from autoslug import AutoSlugField

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='اسم التصنيف')
    slug = AutoSlugField(max_length=255, unique=True, populate_from='name', verbose_name='الاسم المختصر')
    image = models.ImageField(upload_to='category/', null=True, verbose_name='رفع الصورة')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء', blank=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث', blank=True, null=True)

    def __str__(self):
        return self.name
    
    def delete(self, *args, **kwargs):
        # Delete the associated image file
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super(Category, self).delete(*args, **kwargs)



class Product(models.Model):
    image = models.ImageField(upload_to='products/', verbose_name='رفع الصورة')
    name = models.CharField(max_length=255, verbose_name='اسم المنتج')
    description = models.TextField(blank=True, null=True, verbose_name='الوصف')
    category=models.ForeignKey(Category, verbose_name='التصنيف', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='السعر')
    offers = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=0,blank=False, verbose_name='الخصم')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء',blank=True,null=True)
    updated_on = models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث',blank=True,null=True)


    def delete(self, *args, **kwargs):
        # Delete the associated image file
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        
        super(Product, self).delete(*args, **kwargs)
    def __str__(self):
        return self.name

dashboard/forms.py
from django import forms
from menu.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserModel





class DashboardUserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    is_superuser = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check'}), required=False)
    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'is_superuser','password1', 'password2']
        

class DashboardUserUpdateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_superuser = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check'}), required=False)
    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'is_superuser']
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="User Name ", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))


#Category
class CategoryForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}), label='رفع الصورة')
    class Meta:
        model = Category
        fields = ('name', 'image')
        labels = {
            'name': 'اسم التصنيف',
            'image': 'رفع الصورة',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
      
      
# Product  
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('image', 'name', 'description', 'category', 'price', 'offers')
        labels = {
            'image': 'رفع الصورة',
            'name': 'اسم المنتج',
            'description': 'الوصف',
            'category': 'التصنيف',
            'price': 'السعر',
            'offers': 'الخصم',
        }
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control-file'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'offers': forms.NumberInput(attrs={'class': 'form-control'}),
        }

dashboard/views.py
from django.shortcuts import render,redirect,get_object_or_404
from menu.models import *
from .forms import *
from cart.models import *
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def user_list(request):
    users = User.objects.all()
    return render(request, 'user/users_list.html', {'users': users})

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def create_user(request):
    if request.method == 'POST':
        form = DashboardUserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return redirect('user_list')
    else:
        form = DashboardUserRegistrationForm()
    return render(request, 'user/create_user.html', {'form': form})


@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def update_user(request, pk):
    user = User.objects.get(pk=pk)
    if request.method == 'POST':
        form = DashboardUserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect('user_list')
    else:
        form = DashboardUserUpdateForm(instance=user)
    return render(request, 'user/update_user.html', {'form': form})

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def delete_user(request, pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect('user_list')

#Categories
@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category/category_list.html', {'categories': categories})

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'category/create_category.html', {'form': form})

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def edit_category(request, pk):
    category = Category.objects.get(pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            category = form.save()
            return redirect('category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'category/edit_category.html', {'form': form, 'category': category})

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def delete_category(request, pk):
    category = Category.objects.get(pk=pk)
    category.delete()
    return redirect('category_list')


@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def main_dashboard(request):
    product_count=Product.objects.all().count()
    performe_order_count=Order.objects.filter(performed=True).count()
    unperforme_order_count=Order.objects.filter(performed=False).count()
    user_count=User.objects.all().count()
    context = {
        'product_count': product_count,
        'performe_order_count':performe_order_count,
        'unperforme_order_count':unperforme_order_count,
        'user_count':user_count,
        
        
    }
    return render(request,'main_dashboard.html',context)

#Products
@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm()
    
    return render(request, 'product/create_product.html', {'form': form})

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def update_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm(instance=product)
    
    return render(request, 'product/update_product.html', {'form': form, 'product': product})


@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def delete_product(request, pk):
    product = Product.objects.get(pk=pk)
    product.delete()
    return redirect('product_list')
    
    
@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def product_list(request):
    products = Product.objects.all()
    return render(request, 'product/product_list.html', {'products': products})


@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def new_orders(request):
    # Retrieve orders for the logged-in user
    orders = Order.objects.filter(performed=False)

    context = {
        'orders': orders,
    }
    return render(request, 'order/new_orders.html', context)

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def performed_orders(request):
    # Retrieve orders for the logged-in user
    orders = Order.objects.filter(performed=True)

    context = {
        'orders': orders,
    }
    return render(request, 'order/performed_order.html', context)

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def order_details(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    context = {
        'order': order
    }
    return render(request, 'order/order.html', context)

@login_required(login_url='login')  # Redirect to the login page if the user is not authenticated
def performe_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.performed=True
    order.save()
    return redirect('new_orders')
    

    

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})



def logout_user(request):
    logout(request)
    return redirect('home')

dashboard/templates/product/create_product.html
{% extends '../baset.html' %}
{% block title %} 
Create Product
{% endblock %}
{% block products %} 
active
{% endblock %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="card w-50" >
      <div class="card-body">
        <h2 class="card-title text-center"> إنشاء منتج </h2>
  
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
  
          <div class="form-group">
            <label for="id_name">Product Name</label>
            {{ form.name }}
            {% if form.name.errors %}
              <div class="text-danger">
                {% for error in form.name.errors %}
                  <span>{{ error }}</span><br>
                {% endfor %}
              </div>
            {% endif %}
          </div>
  
          <div class="form-group ">
            <label class="btn btn-success text-white" for="id_image">Upload Image</label>
            <div class="input-group">
              <div class="input-group-append">
               {{ form.image }}
              </div>
              <span class="text"></span>
              
            </div>
            <img id="uploaded-image" src="" alt="Uploaded Image" width="100" style="display: none;">
            {% if form.image.errors %}
              <div class="text-danger">
                {% for error in form.image.errors %}
                  <span>{{ error }}</span><br>
                {% endfor %}
              </div>
            {% endif %}
          </div>
  
          <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description }}
            {% if form.description.errors %}
              <div class="text-danger">
                {% for error in form.description.errors %}
                  <span>{{ error }}</span><br>
                {% endfor %}
              </div>
            {% endif %}
          </div>
  
          <div class="form-group">
            <label for="id_category">Category</label>
            {{ form.category }}
            {% if form.category.errors %}
              <div class="text-danger">
                {% for error in form.category.errors %}
                  <span>{{ error }}</span><br>
                {% endfor %}
              </div>
            {% endif %}
          </div>
  
          <div class="form-group">
            <label for="id_price">Price</label>
            {{ form.price }}
            {% if form.price.errors %}
              <div class="text-danger">
                {% for error in form.price.errors %}
                  <span>{{ error }}</span><br>
                {% endfor %}
              </div>
            {% endif %}
          </div>
  
          <div class="form-group">
            <label for="id_offers">Discount</label>
            {{ form.offers }}
            {% if form.offers.errors %}
              <div class="text-danger">
                {% for error in form.offers.errors %}
                  <span>{{ error }}</span><br>
                {% endfor %}
              </div>
            {% endif %}
          </div>
  
          <button type="submit" class="btn btn-primary">Add</button>
        </form>
      </div>
    </div>
  </div>
  
 
  
  <script>
    const fileInput = document.getElementById("id_image");
    
    fileInput.addEventListener("change", function() {
      const fileName = this.files[0].name;
      const button = document.querySelector(".text");
      button.innerHTML = fileName;
      
      const uploadedImage = document.getElementById("uploaded-image");
      uploadedImage.src = URL.createObjectURL(this.files[0]);
      uploadedImage.style.display = "block";
    });
  </script>
{% endblock %}

dashboard/templates/product/product_list.html
{% extends '../baset.html' %}
{% block title %} 
 Products
{% endblock %}

{% block products %} 
active
{% endblock %}
{% block content %}
<div class="text-center">
    <a href="{% url 'create_product' %}" class="btn btn-primary btn-simple btn-icon" role="button" rel="tooltip">
        <i class="now-ui-icons ui-1_simple-add"></i>
      </a>
</div>

<table class="table table-hover table-responsive-md text-center">
  <thead>
      <tr>
        <tr>
            <th class="text-center">اسم المنتج</th>
            <th>السعر</th>
            <th>الخصم</th>
            <th>الصورة</th>
            <th class="text-center">Action</th>
        </tr>
      </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
        <td class="text-center h5">{{ product.name }}</td>
        <td >{{ product.price }}</td>
        <td>{{ product.offers }}</td>
        <td >
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="product Image" width="100" height="100" class="img-thumbnail small-image">
            {% else %}
                No image available
            {% endif %}
        </td>
        <td class="text-center ">
            <a href="{% url 'update_product'  product.id  %}" class="btn btn-success btn-simple btn-icon btn-sm" role="button" rel="tooltip">
                <i class="now-ui-icons ui-2_settings-90"></i>
              </a>
            <button type="button" rel="tooltip" class="btn btn-danger btn-simple btn-icon btn-sm" data-toggle="modal" data-target="#deleteproductModal{{ product.id }}">
                <i class="now-ui-icons ui-1_simple-remove"></i>
              </button>
        </td>
        <!-- Add more columns here as needed -->
    </tr>
    
    <!-- Delete product Modal -->
    <div class="modal fade" id="deleteproductModal{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteproductModalLabel{{ product.id }}" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-center" dir="rtl">
              <h5 class="modal-title " id="deleteproductModalLabel{{ product.id }}">حذف المنتج</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body text-right">
              <p>هل أنت متأكد أنك تريد حذف المنتج {{product.name}}؟</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">إلغاء</button>
              <form action="{% url 'delete_product' product.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">حذف</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- End Delete product Modal -->
{% endfor %}
  </tbody>
</table>

{% endblock %}

dashboard/templates/product/update_product.html
{% extends '../baset.html' %}

{% block title %} 
Update Product
{% endblock %}

{% block content %}

<div class="container d-flex justify-content-center h6">
  <div class="card w-50">
    <div class="card-body ">
      <h2 class="card-title text-center">تعديل منتج </h2>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group ">
          <label for="id_name"> Product Name</label>
          {{ form.name }}
          {% if form.name.errors %}
            <div class="text-danger">
              {% for error in form.name.errors %}
                <span>{{ error }}</span><br>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="form-group ">
          <label class="btn btn-success text-white" for="id_image">Upload Image</label>
          {{ form.image }}
          <span class="text"></span>
          <img id="uploaded-image" src="{{ product.image.url }}" width="100" alt="Uploaded Image" style="display: block;">
          {% if form.image.errors %}
            <div class="text-danger">
              {% for error in form.image.errors %}
                <span>{{ error }}</span><br>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="form-group ">
          <label for="id_description">Description</label>
          {{ form.description }}
          {% if form.description.errors %}
            <div class="text-danger">
              {% for error in form.description.errors %}
                <span>{{ error }}</span><br>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="form-group ">
          <label for="id_category">Category</label>
          {{ form.category }}
          {% if form.category.errors %}
            <div class="text-danger">
              {% for error in form.category.errors %}
                <span>{{ error }}</span><br>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="form-group ">
          <label for="id_price">Price</label>
          {{ form.price }}
          {% if form.price.errors %}
            <div class="text-danger">
              {% for error in form.price.errors %}
                <span>{{ error }}</span><br>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <div class="form-group ">
          <label for="id_offers">Discount</label>
          {{ form.offers }}
          {% if form.offers.errors %}
            <div class="text-danger">
              {% for error in form.offers.errors %}
                <span>{{ error }}</span><br>
              {% endfor %}
            </div>
          {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</div>

<script>
    const fileInput = document.getElementById("id_image");
    fileInput.addEventListener("change", function() {
      const fileName = this.files[0].name;
      const button = document.querySelector(".text");
      button.innerHTML = fileName;
      const uploadedImage = document.getElementById("uploaded-image");
      uploadedImage.src = URL.createObjectURL(this.files[0]);
      uploadedImage.style.display = "block";
    });
  </script>
{% endblock %}